### PR TITLE
Add watch task to gulpfile

### PR DESCRIPTION
**Pull request by kravets-levko**

### CODE REVIEW

**Comment by pwalsh** [comment]
Thanks @kravets-levko 

So @smth now just runs the server with `npm run watch`?

**Comment by kravets-levko** [comment]
@pwalsh Yes. This task will build app, run server and then watch for changes in sass and js files, so @smth don't need to run other tasks

**Comment by smth** [comment]
Watch still doesn't seem to be working. It is now compiling when running `npm run develop` (or `npm run watch`) though.

**Comment by kravets-levko** [comment]
Can you tell me what do you actually do, step by step? I checked this, it worked for me

**Comment by smth** [comment]
1. `npm run watch`
2. Make change to `_app.scss` (nothing appears to happen)
3. Refresh page (no change)
4. `ctrl c` `npm run watch`
5. Refresh page (change present)

**Pull request merged**
